Root3NumTest.class: Root3Num.class Root3NumTest.java
	javac Root3NumTest.java

Root3Num.class: Root3Num.java
	javac Root3Num.java

test: Root3NumTest.class
	java org.junit.runner.JUnitCore Root3NumTest

.PHONY : test
